### ISSUE TITLE
Minihackathon description typos

### ISSUE THREAD

**Issue by mzrimsek** [hacksu/kenthackenough-ui-main#38]
Just read over it and tell me there aren't spots that make 0% sense.

**Comment by NickCrawford** [comment]
I believe this issue is on the wrong repository. @IAPark, will you look into the copywriting on the Hacksu Site?

**Comment by mzrimsek** [comment]
Also dumb for the same reason as the other issue I opened.

Btw you can just assign people to issues and they'll be notified about it IIRC.

**Comment by IAPark** [comment]
Thanks, Totally my fault. I'm assuming this is meant for the Hacksu site?

**Comment by mzrimsek** [comment]
Yeah I did. I opened an issue in the correct repository. Sorry again for the confusion.
